# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Option

on:
  workflow_dispatch:
    inputs:
      bir:
        required: false
        type: string
        default: ""

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        pip install bidict lunar_python colorama
    - name: Run
      run: |
         python bazi.py ${{inputs.opt}}
